cargo-features = ["profile-rustflags"]

[package]
name = "antlr5"
version = "0.1.0"
edition = "2024"

[profile.release]
rustflags = ["-Zpolonius=next"]

[profile.dev]
rustflags = ["-Zpolonius=next"]

[profile.bench]
debug = true # For profiling with samply

[dependencies]
bimap = { version = "0.6.3", features = ["serde"] }
minijinja = "2.21.0"
serde = { version = "1.0.228", features = ["derive", "rc"] }
stacker = "0.1.24"
