cargo-features = ["profile-rustflags"]

[package]
name = "antlr5"
version = "0.1.0"
edition = "2024"

[profile.release]
rustflags = ["-Zpolonius=next"]

[profile.dev]
rustflags = ["-Zpolonius=next"]

[profile.bench]
debug = true # For profiling with samply

[dependencies]
minijinja = "2.21.0"
rayon = "1.12.0"
serde = { version = "1.0.228", features = ["derive", "rc"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
tracing-tree = "0.4.1"
